### ISSUE TITLE
A "MisconfigurationException:" error occurred when I executed the code

### ISSUE THREAD

**Issue by DEROOCE** [elch10/DFS#1]
I downloaded the notebooks and dataset from the project. I executed the codes using jupyter notebook, and the codes were
running successfully until this one:
```python
from pytorch_lightning import Trainer
from test_tube import Experiment
import os

model = CoolSystem(loss_attrs=loss_attrs, class_weights=class_weights)

# PyTorch summarywriter with a few bells and whistles    
exp = Experiment(save_dir=os.getcwd())

# train on cpu using only 10% of the data (for demo purposes)
# pass in experiment for automatic tensorboard logging.    
trainer = Trainer(experiment=exp, max_nb_epochs=20, gpus=[0])

  
trainer.fit(model)
```
and I got the error below:
```
---------------------------------------------------------------------------
MisconfigurationException                 Traceback (most recent call last)
<ipython-input-28-de23d35f9938> in <module>()
     13 
     14 
---> 15 trainer.fit(model)

4 frames
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/data_loading.py in reset_train_dataloader(self, model)
    128                 must be an int. An int k specifies checking validation every k training batches.
    129                 '''
--> 130                 raise MisconfigurationException(m)
    131 
    132             self._percent_range_check('val_check_interval')

MisconfigurationException: 
                When using an infinite DataLoader (e.g. with an IterableDataset or when DataLoader
                does not implement `__len__`) for `train_dataloader`, `Trainer(val_check_interval)`
                must be an int. An int k specifies checking validation every k training batches.
                
```

After searching some help  from Google and Stackoverflow, I still don't get the solution. Is there any way to solve this? Thanks

**Comment by elch10** [comment]
Try to specify `val_check_interval` argument for `Trainer` as some positive integer value https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.trainer.trainer.html#pytorch_lightning.trainer.trainer.Trainer.params.val_check_interval

**Comment by DEROOCE** [comment]
Thanks for your quick reply!
I update my code with setting`val_check_interval=32`, and It fixes the `MisconfigurationException` Error. But It soon reports another error:
```
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py in run_training_epoch(self)
    397         # run epoch
    398         for batch_idx, batch in self.profiler.profile_iterable(
--> 399             enumerate(train_dataloader), "get_train_batch"
    400         ):
    401             # stop epoch if we limited the number of training batches

TypeError: 'NoneType' object is not iterable
```
It seems like the `train_dataloader` has something wrong in the code. Then, I try to read the doc's example, and I find you maybe have a typo in your code:
```python
  @pl.data_loader
  def tng_dataloader(self):
      # REQUIRED
      return DataLoader(MyCustomDataset(X_train, y_train), batch_size=32)
```
In docs, after the decorator, the function name `tng_dataloader` should be `train_dataloader`. Then It fixes all the problems, and the code finally runs successfully.

You may check the example from here : [https://pytorch-lightning.readthedocs.io/en/0.5.3/LightningModule/RequiredTrainerInterface/](https://pytorch-lightning.readthedocs.io/en/0.5.3/LightningModule/RequiredTrainerInterface/)
And thanks for your help again!
